"""add columns to sample table

Revision ID: 0fea067f1b9b
Revises: 425879b84c86
Create Date: 2019-05-13 17:30:11.568936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fea067f1b9b'
down_revision = '425879b84c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('cell_type', sa.String(length=64), nullable=True))
    op.add_column('sample', sa.Column('experiment_id', sa.String(length=10), nullable=True))
    op.add_column('sample', sa.Column('tissue', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'tissue')
    op.drop_column('sample', 'experiment_id')
    op.drop_column('sample', 'cell_type')
    # ### end Alembic commands ###
