"""gene_id table

Revision ID: 175946942786
Revises: 0fea067f1b9b
Create Date: 2019-05-17 16:27:51.225984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175946942786'
down_revision = '0fea067f1b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene_qual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('gene_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=32), nullable=True),
    sa.Column('annotation', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gene_qual')
    # ### end Alembic commands ###
