"""empty message

Revision ID: 425879b84c86
Revises: 
Create Date: 2019-05-12 19:25:05.261824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425879b84c86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SRR_id', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_SRR_id'), 'sample', ['SRR_id'], unique=True)
    op.create_table('gene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.String(length=20), nullable=True),
    sa.Column('barcode', sa.Boolean(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gene_gene_id'), 'gene', ['gene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gene_gene_id'), table_name='gene')
    op.drop_table('gene')
    op.drop_index(op.f('ix_sample_SRR_id'), table_name='sample')
    op.drop_table('sample')
    # ### end Alembic commands ###
