"""empty message

Revision ID: a3ed09de31d6
Revises: b16fff8c495d
Create Date: 2019-05-17 20:05:08.565841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ed09de31d6'
down_revision = 'b16fff8c495d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('GSM_acc', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'GSM_acc')
    # ### end Alembic commands ###
