"""empty message

Revision ID: b16fff8c495d
Revises: 
Create Date: 2019-05-17 19:56:05.531294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16fff8c495d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene_qual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SRR_id', sa.String(length=10), nullable=True),
    sa.Column('experiment_id', sa.String(length=10), nullable=True),
    sa.Column('tissue', sa.String(length=64), nullable=True),
    sa.Column('cell_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_SRR_id'), 'sample', ['SRR_id'], unique=True)
    op.create_table('gene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.String(length=20), nullable=True),
    sa.Column('barcode', sa.Boolean(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gene_gene_id'), 'gene', ['gene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gene_gene_id'), table_name='gene')
    op.drop_table('gene')
    op.drop_index(op.f('ix_sample_SRR_id'), table_name='sample')
    op.drop_table('sample')
    op.drop_table('gene_qual')
    # ### end Alembic commands ###
