"""change GeneQual

Revision ID: c689ba928f0d
Revises: a3ed09de31d6
Create Date: 2019-05-19 15:31:01.845981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c689ba928f0d'
down_revision = 'a3ed09de31d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gene_qual', sa.Column('gene_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_gene_qual_gene_id'), 'gene_qual', ['gene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gene_qual_gene_id'), table_name='gene_qual')
    op.drop_column('gene_qual', 'gene_id')
    # ### end Alembic commands ###
