"""genequalities table

Revision ID: d898ac340ce6
Revises: 175946942786
Create Date: 2019-05-17 16:58:32.385605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd898ac340ce6'
down_revision = '175946942786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gene_qual', 'gene_id')
    op.drop_column('gene_qual', 'annotation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gene_qual', sa.Column('annotation', sa.VARCHAR(length=32), nullable=True))
    op.add_column('gene_qual', sa.Column('gene_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
